In [1]:
import pandas as pd
from requests import get
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [2]:
API_KEY=os.environ.get('BRAPIKEY')

In [124]:
class Stock:
    def __init__(self, ticker):
        self.ticker = ticker
        self.url = f'https://brapi.dev/api/quote/{self.ticker}'
    
    def GetStockInfo(self):
        params = {
            'modules': 'summaryProfile',
            'token': API_KEY,}
        url = self.url
        try:
            req = get(url, params=params)
            data = req.json()
            df = pd.DataFrame(data['results'])
            info = pd.json_normalize(df['summaryProfile'])
            return info
        except Exception as e:
            print(e)


    def GetStockQuote(self):
        params = {
            'token': API_KEY}
        try:
            req = get(self.url, params=params)
            data = req.json()
            return pd.DataFrame(data['results'])
        except Exception as e:
            print(e)      

    def GetHistoricalQuote(self):
        params = {
            'token': API_KEY,
            'range':'3mo',
            'interval':'1d',}
        try:
            req = get(self.url, params=params)
            data = req.json()
            results = pd.json_normalize(data,  'results')
            history = results['historicalDataPrice'][0]
            df = pd.DataFrame(history)
            df['date'] = df['date'].astype('datetime64[s]')
            df['ticker'] = self.ticker
            return df
        except Exception as e:
            print(e)


    def TransformQuotes(data):   
        df = pd.DataFrame(data['results'])
        return df

In [125]:
BANCO = Stock('BBAS3')
INFO = BANCO.GetStockInfo()
INFO

,address1,address2,city,state,country,phone,website,industry,industryKey,industryDisp,sector,sectorKey,sectorDisp,longBusinessSummary,companyOfficers
0,EdifIcio Banco do Brasil,"Quadra 5, Lote B Autarquias Norte Federal Dist...",Brasília,DF,Brazil,55 80 0729 5285,https://www.bb.com.br,Banks - Regional,banks-regional,Banks - Regional,Financial Services,financial-services,Financial Services,"Banco do Brasil S.A., together with its subsid...",[]

In [126]:
qt = BANCO.GetStockQuote()
qt

,currency,shortName,longName,regularMarketChange,regularMarketChangePercent,regularMarketTime,regularMarketPrice,regularMarketDayHigh,regularMarketDayRange,regularMarketDayLow,regularMarketVolume,regularMarketPreviousClose,regularMarketOpen,fiftyTwoWeekRange,fiftyTwoWeekLow,fiftyTwoWeekHigh,symbol,priceEarnings,earningsPerShare,logourl
0,BRL,BRASIL ON NM,Banco do Brasil S.A.,-0.1,-0.412,2025-01-08T18:52:42.000Z,24.15,24.27,23.95 - 24.27,23.95,10902800,24.25,24.2,23.68 - 29.955,23.68,29.955,BBAS3,6.593467,3.633902,https://s3-symbol-logo.tradingview.com/banco-d...

In [127]:
history4 = BANCO.GetHistoricalQuote()
history4

,date,open,high,low,close,volume,adjustedClose,ticker
0,2024-10-09 13:00:00,26.80,26.91,26.35,26.43,19545500,25.7534,BBAS3
1,2024-10-10 13:00:00,26.64,26.64,26.19,26.20,20486300,25.5293,BBAS3
2,2024-10-11 13:00:00,26.28,26.46,26.17,26.33,12175400,25.6560,BBAS3
3,2024-10-14 13:00:00,26.41,26.58,26.28,26.52,11953100,25.8411,BBAS3
4,2024-10-15 13:00:00,26.67,26.74,26.42,26.47,14418700,25.7924,BBAS3
5,2024-10-16 13:00:00,26.50,26.95,26.36,26.76,26028400,26.0750,BBAS3
6,2024-10-17 13:00:00,26.68,26.83,26.50,26.72,12424800,26.0360,BBAS3
7,2024-10-18 13:00:00,26.77,26.97,26.63,26.69,15980000,26.0068,BBAS3
8,2024-10-21 13:00:00,26.69,26.96,26.54,26.62,25128900,25.9386,BBAS3
9,2024-10-22 13:00:00,26.55,26.60,26.27,26.30,27391300,25.6268,BBAS3
10,2024-10-23 13:00:00,26.30,26.44,26.16,26.33,12126400,25.6560,BBAS3
11,2024-10-24 13:00:00,26.41,26.46,26.25,26.36,8727600,25.6852,BBAS3
12,2024-10-25 13:00:00,26.36,26.50,26.25,26.37,7807800,25.6950,BBAS3
13,2024-10-28 13:00:00,26.50,26.55,26.19,26.32,18192100,25.6463,BBAS3
14,2024-10-29 13:00:00,26.37,26.45,26.15,26.17,13433400,25.5001,BBAS3
15,2024-10-30 13:00:00,26.18,26.39,26.09,26.37,14377600,25.6950,BBAS3
16,2024-10-31 13:00:00,26.33,26.46,26.23,26.33,11163300,25.6560,BBAS3
17,2024-11-01 13:00:00,26.35,26.40,26.01,26.09,15216400,25.4222,BBAS3
18,2024-11-04 13:00:00,26.27,26.42,26.15,26.24,12169700,25.5683,BBAS3
19,2024-11-05 13:00:00,26.27,26.29,26.06,26.25,14050600,25.5781,BBAS3
20,2024-11-06 13:00:00,26.10,26.37,25.94,26.30,12445400,25.6268,BBAS3
21,2024-11-07 13:00:00,26.30,26.64,26.13,26.19,11667700,25.5196,BBAS3
22,2024-11-08 13:00:00,26.10,26.13,25.90,25.99,15878800,25.3247,BBAS3
23,2024-11-11 13:00:00,26.10,26.10,25.95,26.01,10515100,25.3442,BBAS3
24,2024-11-12 13:00:00,26.01,26.09,25.80,25.95,15391500,25.2857,BBAS3
25,2024-11-13 13:00:00,25.99,26.07,25.88,25.95,27198100,25.2857,BBAS3
26,2024-11-14 13:00:00,25.78,25.79,24.79,25.37,80824400,24.7206,BBAS3
27,2024-11-18 13:00:00,25.38,25.81,25.34,25.71,23386200,25.0519,BBAS3
28,2024-11-19 13:00:00,25.77,25.95,25.64,25.85,29342400,25.1883,BBAS3
29,2024-11-21 13:00:00,25.80,25.85,25.23,25.26,31594700,24.6134,BBAS3
30,2024-11-22 13:00:00,25.46,25.60,25.22,25.60,13737200,24.9447,BBAS3
31,2024-11-25 13:00:00,25.79,25.84,25.60,25.75,36581800,25.0909,BBAS3
32,2024-11-26 13:00:00,25.36,25.78,25.21,25.67,22044000,25.4914,BBAS3
33,2024-11-27 13:00:00,25.71,25.78,25.11,25.22,20884000,25.0445,BBAS3
34,2024-11-28 13:00:00,25.19,25.21,24.41,24.48,26984000,24.3096,BBAS3
35,2024-11-29 13:00:00,24.52,24.84,24.32,24.77,22743200,24.5976,BBAS3
36,2024-12-02 13:00:00,24.80,24.92,24.46,24.57,21487000,24.3990,BBAS3
37,2024-12-03 13:00:00,24.71,24.90,24.65,24.87,22179600,24.6969,BBAS3
38,2024-12-04 13:00:00,24.89,25.33,24.80,25.17,19375200,24.9948,BBAS3
39,2024-12-05 13:00:00,25.39,25.60,25.27,25.48,18238400,25.3027,BBAS3
40,2024-12-06 13:00:00,25.25,25.35,24.50,24.73,33652400,24.5579,BBAS3
41,2024-12-09 13:00:00,24.84,24.89,24.42,24.67,17774100,24.4983,BBAS3
42,2024-12-10 13:00:00,24.78,24.92,24.52,24.83,15266700,24.6572,BBAS3
43,2024-12-11 13:00:00,24.90,25.65,24.67,25.36,29090900,25.1835,BBAS3
44,2024-12-12 13:00:00,25.05,25.09,24.59,24.85,19824400,24.8500,BBAS3
45,2024-12-13 13:00:00,24.85,24.99,24.50,24.51,17217300,24.5100,BBAS3
46,2024-12-16 13:00:00,24.52,24.60,24.13,24.16,16061900,24.1600,BBAS3
47,2024-12-17 13:00:00,24.25,24.49,24.01,24.42,27695800,24.4200,BBAS3
48,2024-12-18 13:00:00,24.40,24.40,23.73,23.74,29428400,23.7400,BBAS3
49,2024-12-19 13:00:00,23.81,24.05,23.75,23.89,16306300,23.8900,BBAS3
50,2024-12-20 13:00:00,23.92,24.14,23.87,24.08,49200400,24.0800,BBAS3
51,2024-12-23 13:00:00,24.07,24.13,23.88,23.92,12708100,23.9200,BBAS3
52,2024-12-26 13:00:00,23.95,24.40,23.93,24.20,15208900,24.2000,BBAS3
53,2024-12-27 13:00:00,24.34,24.37,24.11,24.11,10465000,24.1100,BBAS3
54,2024-12-30 13:00:00,24.10,24.33,24.09,24.17,27146200,24.1700,BBAS3
55,2025-01-02 13:00:00,24.17,24.28,23.84,23.92,14492900,23.9200,BBAS3
56,2025-01-03 13:00:00,23.92,24.06,23.68,23.74,13778900,23.7400,BBAS3
57,2025-01-06 13:00:00,23.98,24.05,23.81,23.96,12112300,23.9600,BBAS3
58,2025-01-07 19:07:37,24.14,24.38,24.02,24.25,10033100,24.2500,BBAS3